base_model: google/gemma-3-1b-it

chat_template: gemma3
eot_tokens:
  - <end_of_turn>

datasets:
  - path: cgato/SlimOrcaDedupCleaned
    type: chat_template
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

val_set_size: 0
output_dir: ./outputs/dft-gemma-3-1b

use_dft: true

sequence_len: 1024

gradient_accumulation_steps: 4
micro_batch_size: 1
max_steps: 1000
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 5e-5
warmup_ratio: 0.1
weight_decay: 0.0

bf16: auto
tf32: true

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
logging_steps: 1
attn_implementation: flash_attention_2
