base_model: Unbabel/7B_mistral_all_mc4_parallel_eos_20b_20b_ckpt
model_type: AutoModelForCausalLM
tokenizer_type: LlamaTokenizer
# is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false
#Unbabel/TowerBlocks-v1-MT-only
datasets:
  - path: Unbabel/Tower-v1-0405
    type: sharegpt
    conversation: chatml

chat_template: chatml

dataset_prepared_path: 
val_set_size: 0
output_dir: /mnt/cephfs-nvme/nunomg/axolotl/Tower_v1_ckpts/all_2703_OHwCPT_2epochs_w_sys_lora/

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

adapter: lora
lora_model_dir:
lora_r: 32
lora_alpha: 16
lora_modules_to_save: [embed_tokens, lm_head]
lora_dropout: 0.05
lora_target_linear: true

wandb_project: translation-llm
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 8
micro_batch_size: 8
eval_batch_size: 1
num_epochs: 2
optimizer: adamw_torch
lr_scheduler: cosine
learning_rate: 7e-4

# neftune_noise_alpha: 5

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
local_rank:
logging_steps:
xformers_attention:
flash_attention: true
flash_attn_cross_entropy: false
flash_attn_rms_norm: true
flash_attn_fuse_qkv: false
flash_attn_fuse_mlp: false

warmup_steps: 125
eval_steps:
eval_sample_packing: False
eval_table_size:
save_steps:
save_total_limit:
debug:
deepspeed: /mnt/cephfs-nvme/nunomg/axolotl/deepspeed/zero3.json # multi-gpu only
weight_decay: 0.01
fsdp:
fsdp_config:
tokens:
  - <|im_start|>
special_tokens:
  # bos_token: "<s>"
  eos_token: "<|im_end|>"
  # unk_token: "<unk>"