# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: true
  poem: false
  sequence_diagrams: false
  auto_review:
    enabled: true
    drafts: false
    auto_incremental_review: true
chat:
  auto_reply: true
