base_model: ibm-granite/granite-speech-3.3-2b
# Remove model_type to let Axolotl auto-detect the correct model type
# model_type: GraniteSpeechForConditionalGeneration
# Enable trust_remote_code to use the model's custom code
trust_remote_code: true
# Mark as multimodal since this is a speech model
is_multimodal: true

hub_model_id: syvai/gsp

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

datasets:
  - path: syvai/coral-tts-asr
    type:  # leave empty to load pre-tokenized
dataset_prepared_path: last_run_prepared
val_set_size: 0.02
output_dir: ./outputs/out
eval_sample_packing: False

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 16
micro_batch_size: 1
num_epochs: 3
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 2e-5

bf16: auto
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_steps: 20
evals_per_epoch: 5
saves_per_epoch: 5
weight_decay: 0.05

#save_first_step: true  # uncomment this to validate checkpoint saving works with your config