base_model: Qwen/Qwen3-8B
# Automatically upload checkpoint and final model to HF
# hub_model_id: username/custom_model_name

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_glu_activation: true
# liger_fused_linear_cross_entropy: true

chat_template: qwen3
datasets:
  - path: mlabonne/FineTome-100k
    type: chat_template
    split: train[:20%]
    field_messages: conversations
    message_property_mappings:
      role: from
      content: value

dataset_prepared_path: last_run_prepared
# val_set_size: 0.02
output_dir: ./outputs/out

sequence_len: 1024
# sample_packing: true

wandb_project: dist-parallel
wandb_entity: axolotl-ai
wandb_watch:
wandb_name: dp_shard-4-dp_replicate-2-bsz-1-gradaccm-1
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: adamw_torch_8bit
lr_scheduler: cosine
learning_rate: 2e-5

bf16: auto
tf32: false

# context_parallel_size: 8
# tensor_parallel_size: 2
dp_replicate_size: 2
dp_shard_size: 4

# gradient_checkpointing: true
# gradient_checkpointing_kwargs:
#   use_reentrant: false
resume_from_checkpoint:
logging_steps: 1
flash_attention: true
include_tokens_per_second: true

warmup_steps: 100
# evals_per_epoch:
saves_per_epoch: 1
weight_decay: 0.0
special_tokens:
  pad_token: <|finetune_right_pad_id|>
  eos_token: <|eot_id|>

logging:
  level: DEBUG
fsdp_version: 2
fsdp_config:
  offload_params: false
  state_dict_type: FULL_STATE_DICT
  auto_wrap_policy: TRANSFORMER_BASED_WRAP
  transformer_layer_cls_to_wrap: Qwen3DecoderLayer
  reshard_after_forward: true
  activation_checkpointing: true

# save_first_step: true  # uncomment this to validate checkpoint saving works with your config
