base_model: Qwen/Qwen2.5-0.5B
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: tatsu-lab/alpaca
    type: alpaca
    split: train[:1%]

dataset_prepared_path:
val_set_size: 0.05
output_dir: ./outputs/qwen2-muon-fsdp2

adapter:
lora_model_dir:

sequence_len: 2048
sample_packing: false
pad_to_sequence_len: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 1
max_steps: 10000

optimizer: muon
learning_rate: 0.02
weight_decay: 0.01
lr_scheduler: cosine
lr_scheduler_kwargs:

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: false
tf32: false

gradient_checkpointing: false
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 5
evals_per_epoch: 0
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:

fsdp:
  - full_shard
  - auto_wrap

fsdp_config:
  fsdp_version: 2
  fsdp_offload_params: false
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: Qwen2DecoderLayer
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_cpu_ram_efficient_loading: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_reshard_after_forward: true

special_tokens:
