base_model: Qwen/Qwen3-8B
# Automatically upload checkpoint and final model to HF
# hub_model_id: 

load_in_8bit: false
load_in_4bit: false
strict: false

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_glu_activation: true
liger_rms_norm: true
liger_layer_norm: true

pretraining_dataset:
  - path: allenai/c4
    name: en
    split: train
    type: pretrain

output_dir: ./outputs/out_test_2

sequence_len: 1024

sample_packing: true
flex_attention: true
pad_to_sequence_len: true

flex_attn_compile_kwargs:
  dynamic: false
  mode: max-autotune-no-cudagraphs

qat:
  activation_dtype: int8
  weight_dtype: int8
  group_size: 256
  fake_quant_after_n_steps: 2
  quantize_with_ptq: true

wandb_project: qat
wandb_entity:
wandb_watch:
wandb_name: base
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 2
max_steps: 4
optimizer: adamw_torch_fused
lr_scheduler: cosine
learning_rate: 2e-5

bf16: true
tf32: true

resume_from_checkpoint:
logging_steps: 1

warmup_steps: 10
eval_strategy: "no"
# evals_per_epoch: 4
saves_per_epoch: 0
weight_decay: 0.0
fsdp:
  - full_shard
  - auto_wrap
fsdp_config:
  fsdp_version: 2
  fsdp_offload_params: false
  fsdp_cpu_ram_efficient_loading: true
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen3DecoderLayer
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_reshard_after_forward: true
  fsdp_activation_checkpointing: true

special_tokens:
