base_model: axolotl-ai-co/Mistral-Medium-3.5-128B-BF16
processor_type: AutoProcessor

plugins:
  - axolotl.integrations.cut_cross_entropy.CutCrossEntropyPlugin

load_in_4bit: true

skip_prepare_dataset: true
remove_unused_columns: false
sample_packing: false

# sample dataset below requires downloading image in advance
# wget https://huggingface.co/datasets/Nanobit/text-vision-2k-test/resolve/main/African_elephant.jpg
datasets:
  - path: Nanobit/text-vision-2k-test
    type: chat_template

dataset_prepared_path: last_run_prepared
val_set_size: 0.1
output_dir:

adapter: qlora
lora_model_dir:

sequence_len: 2048

lora_r: 32
lora_alpha: 16
lora_dropout: 0
lora_target_modules: 'model.language_model.layers.[\d]+.(mlp|self_attn).(up|down|gate|q|k|v|o)_proj'

lora_mlp_kernel: true
lora_qkv_kernel: true
lora_o_kernel: true

wandb_project:
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
max_steps: 10
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.0002

bf16: auto
tf32: false

gradient_checkpointing: true
resume_from_checkpoint:
logging_steps: 1
flash_attention: true

warmup_ratio: 0.1
evals_per_epoch: 1
saves_per_epoch: 1
