"""Generate lightweight Click option metadata for the Axolotl CLI."""

from __future__ import annotations

import json
from pathlib import Path

from pydantic import BaseModel

from axolotl.cli.utils.args import ConfigOption, _strip_optional_type
from axolotl.utils.schemas.config import AxolotlInputConfig

DEFAULT_OUTPUT = Path("src/axolotl/cli/config_options.py")


def _is_pydantic_model(field_type: type) -> bool:
    try:
        return isinstance(field_type, type) and issubclass(field_type, BaseModel)
    except TypeError:
        return False


def _get_field_description(field) -> str | None:
    if field.description:
        return field.description
    if field.json_schema_extra and isinstance(field.json_schema_extra, dict):
        return field.json_schema_extra.get("description")
    return None


def _click_type_name(field_type: type) -> str | None:
    return {str: "str", int: "int", float: "float"}.get(field_type)


def _option_for_scalar(name: str, field) -> ConfigOption:
    field_type = _strip_optional_type(field.annotation)
    description = _get_field_description(field)
    option_name = f"--{name.replace('_', '-')}"
    if field_type is bool:
        return (
            (f"{option_name}/--no-{name.replace('_', '-')}",),
            None,
            None,
            description,
        )
    return ((option_name,), None, None, description)


def _option_for_nested(parent_name: str, sub_name: str, sub_field) -> ConfigOption:
    sub_type = _strip_optional_type(sub_field.annotation)
    cli_name = f"{parent_name}.{sub_name}".replace("_", "-")
    param_name = f"{parent_name}__{sub_name}"
    description = _get_field_description(sub_field)

    if sub_type is bool:
        return ((f"--{cli_name}/--no-{cli_name}",), param_name, None, description)
    return ((f"--{cli_name}",), param_name, _click_type_name(sub_type), description)


def _format_string(value: str | None) -> str:
    if value is None:
        return "None"
    if '"' in value and "'" not in value:
        return ascii(value)
    return json.dumps(value)


def _format_param_decls(param_decls: tuple[str, ...]) -> list[str]:
    decls = ", ".join(_format_string(decl) for decl in param_decls)
    if len(param_decls) == 1:
        decls += ","
    single_line = f"        ({decls}),"
    if len(single_line) <= 88:
        return [single_line]
    return [
        "        (",
        *(f"            {_format_string(decl)}," for decl in param_decls),
        "        ),",
    ]


def _format_option(option: ConfigOption) -> str:
    param_decls, param_name, click_type_name, description = option
    param_name_literal = _format_string(param_name)
    click_type_literal = _format_string(click_type_name)
    description_literal = _format_string(description)
    return "\n".join(
        [
            "    (",
            *_format_param_decls(param_decls),
            f"        {param_name_literal},",
            f"        {click_type_literal},",
            f"        {description_literal},",
            "    ),",
        ]
    )


def generate_options() -> list[ConfigOption]:
    options = []
    for name, field in AxolotlInputConfig.model_fields.items():
        field_type = _strip_optional_type(field.annotation)
        if _is_pydantic_model(field_type):
            for sub_name, sub_field in field_type.model_fields.items():
                options.append(_option_for_nested(name, sub_name, sub_field))
        else:
            options.append(_option_for_scalar(name, field))
    return options


def generate_content() -> str:
    options = generate_options()
    return "\n".join(
        [
            '"""Generated Click option metadata for Axolotl config overrides."""',
            "",
            "# Generated by axolotl generate-cli-config-options.",
            "# Do not edit by hand.",
            "",
            "from __future__ import annotations",
            "",
            "AXOLOTL_CONFIG_CLI_OPTIONS = (",
            *(_format_option(option) for option in options),
            ")",
            "",
        ]
    )


def write_options(output: Path = DEFAULT_OUTPUT, check: bool = False) -> None:
    content = generate_content()
    if check:
        current = output.read_text(encoding="utf-8") if output.exists() else ""
        if current != content:
            raise SystemExit(f"{output} is out of date")
        print(f"{output} is up to date")
        return

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")
    print(f"Wrote {output}")


def main() -> None:
    write_options()
