name: Debug Commit Message

on:
  pull_request:
  push:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug all commit message contexts
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "github.event.head_commit.message: '${{ github.event.head_commit.message }}'"
          echo "github.event.commits[0].message: '${{ github.event.commits[0].message }}'"
          echo "github.event.pull_request.head.commit.message: '${{ github.event.pull_request.head.commit.message }}'"
          echo "github.event.pull_request.title: '${{ github.event.pull_request.title }}'"
          echo "Contains test [skip-e2e] in head_commit.message: ${{ contains(github.event.head_commit.message, '[skip-e2e]') }}"
          echo "Contains test [skip-e2e] in commits[0].message: ${{ contains(github.event.commits[0].message, '[skip-e2e]') }}"
      
      - name: This step should be SKIPPED when [skip-e2e] is in commit message
        if: ${{ ! contains(github.event.head_commit.message, '[skip-e2e]') && ! contains(github.event.commits[0].message, '[skip-e2e]') }}
        run: |
          echo "❌ E2E TESTS WOULD RUN - [skip-e2e] NOT DETECTED"
          echo "This step should NOT appear if skip logic is working"
      
      - name: This step should RUN when [skip-e2e] is detected
        if: ${{ contains(github.event.head_commit.message, '[skip-e2e]') || contains(github.event.commits[0].message, '[skip-e2e]') }}
        run: |
          echo "✅ E2E TESTS SKIPPED - [skip-e2e] DETECTED"
          echo "Skip logic is working correctly!"