name: docker-e2e-tests

on:
  merge_group:
  push:
    branches:
      - "main"
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/*.yml"
      - "cicd/cicd.sh"
      - "cicd/cicd_cuda_kernels.sh"
      - "cicd/prepare_hf_cache.sh"
      - "cicd/Dockerfile-uv.jinja"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
    paths:
      - "**.py"
      - "pyproject.toml"
      - ".github/workflows/*.yml"
      - "cicd/cicd.sh"
      - "cicd/cicd_cuda_kernels.sh"
      - "cicd/prepare_hf_cache.sh"
      - "cicd/Dockerfile-uv.jinja"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-e2e:
    if: >
      github.event_name != 'pull_request' ||
      (
        !github.event.pull_request.draft &&
        contains(github.event.pull_request.labels.*.name, 'run-gpu-tests') &&
        (github.event.action != 'labeled' || github.event.label.name == 'run-gpu-tests')
      )
    uses: ./.github/workflows/docker-e2e-jobs.yml
    secrets: inherit
