name: docker-multigpu-tests-biweekly

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,4" # Runs at 00:00 UTC every monday & thursday

permissions:
  contents: read
  pull-requests: read

jobs:
  run-multigpu:
    uses: ./.github/workflows/multi-gpu-e2e-jobs.yml
    secrets: inherit
